name: uenv
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _x86_64-microarch-level=3
  - absl-py=2.1.0
  - alsa-lib=1.2.14
  - aom=3.9.1
  - asttokens=3.0.0
  - astunparse=1.6.3
  - attr=2.5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.6.15
  - cached-property=1.5.2
  - cairo=1.18.4
  - certifi=2025.6.15
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - cpuonly=2.0
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.14
  - decorator=5.2.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.6.4
  - ffmpeg=7.1.1
  - filelock=3.17.0
  - flatbuffers=24.12.23
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freeglut=3.2.2
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.3.2
  - gast=0.5.3
  - gdk-pixbuf=2.42.12
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.67.1
  - h5py=3.13.0
  - harfbuzz=10.4.0
  - hdf5=1.14.3
  - icu=75.1
  - idna=3.7
  - imath=3.1.12
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - ipykernel=6.29.5
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jasper=4.2.5
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kaldi=5.5.1112
  - keras=3.6.0
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - level-zero=1.22.3
  - libabseil=20240722.0
  - libaec=1.1.3
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libass=0.17.3
  - libavif16=1.3.0
  - libblas=3.9.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.6
  - libclang13=20.1.6
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.0.30
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcurl=8.14.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libde265=1.0.15
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libgrpc=1.67.1
  - libheif=1.19.7
  - libhwloc=2.11.2
  - libiconv=1.18
  - libidn2=2.3.4
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm20=20.1.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopencv=4.11.0
  - libopengl=1.7.0
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.5
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.50.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=256.9
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libudev1=257.4
  - libunistring=0.9.10
  - libunwind=1.6.2
  - liburing=2.9
  - libusb=1.0.29
  - libuuid=2.38.1
  - libuv=1.51.0
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.6
  - lz4-c=1.9.4
  - markdown=3.8
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.0
  - mkl=2024.2.2
  - mkl-service=2.4.2
  - mkl_fft=1.3.14
  - mkl_random=1.2.10
  - ml_dtypes=0.4.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - namex=0.0.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.4.2
  - nomkl=3.0
  - numpy=2.2.5
  - numpy-base=2.2.5
  - ocl-icd=2.3.3
  - opencl-headers=2024.10.24
  - opencv=4.11.0
  - openexr=3.3.2
  - openfst=1.8.3
  - openh264=2.6.0
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.5.1
  - opt_einsum=3.3.0
  - optree=0.14.1
  - p11-kit=0.24.1
  - packaging=24.2
  - pango=1.56.3
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=25.1
  - pixman=0.46.0
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - protobuf=5.28.3
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - py-opencv=4.11.0
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=24.3.25
  - python_abi=3.12
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qt6-main=6.8.3
  - rav1e=0.7.1
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - sdl2=2.32.54
  - sdl3=3.2.14
  - setuptools=72.1.0
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - sqlite=3.31.1
  - stack_data=0.6.3
  - svt-av1=3.0.2
  - sympy=1.13.3
  - tbb=2021.13.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=2.1.0
  - tk=8.6.13
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5.1
  - traitlets=5.14.3
  - wayland=1.23.1
  - wayland-protocols=1.44
  - wcwidth=0.2.13
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - addict==2.4.0
      - attrs==25.3.0
      - blinker==1.9.0
      - click==8.2.1
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dash==3.1.1
      - fastjsonschema==2.21.1
      - flask==3.1.1
      - flask-cors==6.0.1
      - fonttools==4.58.5
      - h11==0.16.0
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - narwhals==1.46.0
      - nbformat==5.10.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - open3d==0.19.0
      - outcome==1.3.0.post0
      - pandas==2.3.1
      - plotly==6.2.0
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - pytz==2025.2
      - referencing==0.36.2
      - retrying==1.4.0
      - rpds-py==0.26.0
      - scikit-learn==1.7.0
      - scipy==1.16.0
      - selenium==4.33.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - threadpoolctl==3.6.0
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - trio==0.30.0
      - trio-websocket==0.12.2
      - triton==3.3.1
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
      - wsproto==1.2.0
prefix: /home/tef-ai-matters/anaconda3/envs/uenv
